### ISSUE TITLE
Build failure on Edel

### ISSUE THREAD

**Issue by SheLikesCloth** [eArmada8/ed8pkg2gltf#5] opened 2023-05-07 02:32 UTC
# Problem
`build_collada.py` failed when using Edel’s model from CS4.

## Reproduce

Edel’s pkg file attached to ease in troubleshooting: [C_CHR735.zip](https://github.com/eArmada8/ed8pkg2gltf/files/11413761/C_CHR735.zip)

* Extract `C_CHR735.pkg` from `assets.pka` from Steam CS4
* Decompile `C_CHR735.pkg`: 
    - Place `C_CHR735.pkg`, `ed8pkg2gltf.py`, and `lib_fmtibvb.py` into folder without other files
    - Run `ed8pkg2gltf.py`
 * Compile 
    - Navigate into `C_CHR735`
    - Paste the following files into folder:
         + `build_collada.py`
         + `CSIVAssetImportTool.exe`
         + `lib_fmtibvb.py`
         + `PhyreAssetDatabase.dll`
         + `PhyreAssetDatabaseD3D11.db`
         + `PhyreAssetDatabaseUnmanaged.dll`
         + `PhyreAssetProcessorDO.dll`
         + `PhyreAssetScript.lua`
         + `PhyreAssetServices.dll`
         + `PhyreAssetSpec.xml`
         + `PhyreDummyShaderCreator.exe`
         + `replace_shader_references.py`
         + `SQLite.Interop.dll`
         + `System.Data.SQLite.dll`
         + `write_pkg.py`
    - Run `build_collada.py`

# Result
This is the information I got from running `python build_collada.py` from the terminal:
```
...
Reading submesh shadowmodel_09...
Adding materials...
Adding skeleton...
Traceback (most recent call last):
  File "...\build_collada.py", line 883, in <module>
    build_collada(models[i])
  File "...\build_collada.py", line 859, in build_collada
    skeleton = add_bone_info(metadata['heirarchy'])
  File "...\build_collada.py", line 339, in add_bone_info
    skeleton = calc_abs_matrix(child, skeleton)
  File "...\build_collada.py", line 295, in calc_abs_matrix
    skeleton = calc_abs_matrix(child, skeleton)
  File "...\build_collada.py", line 295, in calc_abs_matrix
    skeleton = calc_abs_matrix(child, skeleton)
  File "...\build_collada.py", line 295, in calc_abs_matrix
    skeleton = calc_abs_matrix(child, skeleton)
  File "...\build_collada.py", line 291, in calc_abs_matrix
    skeleton[node]['inv_matrix'] = numpy.linalg.inv(skeleton[node]['abs_matrix'])
  File "<__array_function__ internals>", line 200, in inv
  File "...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\linalg\linalg.py", line 538, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\linalg\linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

# File version: 
2.2.0 (2023-05-01)

**Comment by eArmada8** [comment] 2023-06-01 19:20
There are two invalid matrices in Edel's skeleton, center_point and L_hand_point (line 4511 and 6155 in metadata.json, respectively).  Both are [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,1]], which is mathematically invalid for a rotation matrix.  If you correct them to [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]], then the model should compile fine.  Angelica's skeleton (CHR019) has the same issue.

I will not be "fixing" this as it is not a bug in my script.  I have no idea why mathematically-invalid matrices are in the skeleton; I have to assume that someone at Falcom inputted them by hand because no software would have come up with them.  I think it's best that errors due to hand-coded errors are fixed by hand, because any attempt I make at detecting these errors and fixing them in a robust manner would have unintended consequences that may be very difficult to track down.  (In other words, if they are not fixed by hand, there may be crazy distortions in the model and you would not know why.  After all, I cannot guarantee that the only errors will be mistyped identity matrices.)

**Closed** 2023-06-01 19:21 UTC

**Comment by eArmada8** [comment] 2023-08-03 22:39
I posted a workaround, with this commit: https://github.com/eArmada8/ed8pkg2gltf/commit/190045ac91a1e5f182df70da3a4cefe813c358e6
